[toolchain]
# How to update version:
#  1. update `channel = "RUST_VERSION"`
#  2. update the nightly version:
#     a) Find the latest nightly release that matches RUST_VERSION here: https://github.com/oxalica/rust-overlay/tree/master/manifests/nightly/2024
#     b) update `channel = "nightly-OLD_DATE"` below

channel = "1.78.0" # check ^^^ when changing this
# 
# channel = "nightly-2024-03-17" # 1.78.0 nightly to be able to use unstable features
