on:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Do not add permissions here! Configure them at the job level!
permissions: {}

jobs:
  test-latest-release:
    runs-on: [ubuntu-22.04]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt install -y expect ncat ripgrep

      - name: remove everything except some ci scripts
        run: |
          mkdir temp
          mv ./ci/test_latest_release.sh temp
          mv ./ci/get_latest_release_git_files.sh temp
          mv ./ci/rust_http_server temp
          find . -mindepth 1 -maxdepth 1 ! -name 'temp' -exec rm -rf {} +

      - name: Get all git files of the latest basic-cli release
        run: ./temp/get_latest_release_git_files.sh

      - name: Use ./ci/test_latest_release.sh of the latest git main
        run: mv -f ./temp/test_latest_release.sh ./ci/

      - name: Remove things that dont work on musl
        run: |
          rm ./examples/file-accessed-modified-created-time.roc
          sed -i.bak -e '/time_accessed!,$/d' -e '/time_modified!,$/d' -e '/time_created!,$/d' -e '/^time_accessed!/,/^$/d' -e '/^time_modified!/,/^$/d' -e '/^time_created!/,/^$/d' -e '/^import Utc exposing \[Utc\]$/d' ./platform/File.roc
          rm ./platform/File.roc.bak

      - name: Run all tests with latest roc release + latest basic-cli release
        run: EXAMPLES_DIR=./examples/ ./ci/test_latest_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
